server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-cperjq7sc6pc73a319ug-a:5432/fatecjava_3rbg
        username: fatecjava
        password: rD7NIJNpRZhrqK0DkPpOTYTm6DT5wPbV
        driver-class-name: org.postgresql.Driver
        initialize: true

    jpa: 
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true

    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres
